export const customerActionTypes = {
    SET_CUSTOMERS : 'SET_CUSTOMERS',
    FETCH_CUSTOMERS: 'FETCH_CUSTOMERS',
    SET_CUSTOMERS_LOADING_STATUS: 'SET_CUSTOMER_LOADING_STATUS',
    PICK_CUSTOMER: 'PICK_CUSTOMER'
}