<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Learning\CreateDb\Model;

class Product extends \Magento\Catalog\Model\Product
{
    public function getName()
    {
        return parent::getName()."-added"; // TODO: Change the autogenerated stub
    }
}
